name: Java CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          cache-dependency-path: "Expense Tracker/pom.xml"

      - run: mvn clean test
      working-directory: "Expense Tracker"
    
